data:
  table: public.real_estate_dataset_clean
  out: data/processed/dataset.csv

train:
  target: price
  test_size: 0.2
  random_state: 42

model:
  n_estimators: 500
  max_depth: 8
  loss_function: RMSE

metrics:
  scoring:
    - neg_root_mean_squared_error
    - neg_mean_absolute_error
    - neg_mean_absolute_percentage_error


s3:
  bucket: s3-student-mle-20251010-5a382f9c3d
  model_key: models/real_estate/model.pkl
  endpoint_url: https://storage.yandexcloud.net
